repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.13.1
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: typecheck (dmypy + fine-grained cache)
        entry: .hooks/typecheck.sh
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
