name: Pytests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: '0'
          submodules: 'true'

      - name: Install uv & set Python
        uses: astral-sh/setup-uv@v7.0.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true  # persists uv cache between runs

      - name: Sync project
        run: uv sync --locked --all-extras --dev

      - name: Run tests (pytest)
        run: uv run pytest -v -s
